// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	DeleteProduct(ctx context.Context, id int) (int, error)
	GetProductById(ctx context.Context, id int) (Product, error)
	GetProductsByPlatform(ctx context.Context, platformID int) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (int, error)
}

var _ Querier = (*Queries)(nil)
