// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error)
	DeletePlatform(ctx context.Context, id int) (int, error)
	GetPlatform(ctx context.Context, id int) (Platform, error)
	GetPlatforms(ctx context.Context) ([]Platform, error)
	UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (int, error)
}

var _ Querier = (*Queries)(nil)
