services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:?DB_USERNAME is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      POSTGRES_DB: products
    ports:
      - "5432:5432"