-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: changelog.yml
-- Ran at: 4/18/26, 9:26 PM
-- Against: postgres@jdbc:postgresql://localhost:5432/products
-- Liquibase version: 5.0.2
-- *********************************************************************

-- Changeset changelogs/initial_tables.yml::tagDatabase-v1.0.0::jlpdeveloper
INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID, TAG) VALUES ('tagDatabase-v1.0.0', 'jlpdeveloper', 'changelogs/initial_tables.yml', NOW(), 1, '9:19241f4e7bc7a9aa36aa862d15e66697', 'tagDatabase', '', 'EXECUTED', NULL, 'v1.0.0', '5.0.2', '6565605040', 'v1.0.0');

-- Changeset changelogs/initial_tables.yml::create-platforms-table::jlpdeveloper
CREATE TABLE public.platforms (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT platforms_pkey PRIMARY KEY (id));

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-platforms-table', 'jlpdeveloper', 'changelogs/initial_tables.yml', NOW(), 2, '9:b7ba64976d53dd10567d2960f657fc30', 'createTable tableName=platforms', '', 'EXECUTED', NULL, 'v1.0.0', '5.0.2', '6565605040');

-- Changeset changelogs/initial_tables.yml::create-products-table::jlpdeveloper
CREATE TABLE public.products (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, platform_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, description TEXT, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT products_pkey PRIMARY KEY (id));

ALTER TABLE public.products ADD CONSTRAINT fk_products_platforms FOREIGN KEY (platform_id) REFERENCES public.platforms (id) ON DELETE CASCADE;

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-products-table', 'jlpdeveloper', 'changelogs/initial_tables.yml', NOW(), 3, '9:00b38a2f6fc8224e2b2bf6220837718e', 'createTable tableName=products; addForeignKeyConstraint baseTableName=products, constraintName=fk_products_platforms, referencedTableName=platforms', '', 'EXECUTED', NULL, 'v1.0.0', '5.0.2', '6565605040');

-- Changeset changelogs/initial_tables.yml::create-flows-table::jlpdeveloper
CREATE TABLE public.flows (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL, description TEXT, created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT flows_pkey PRIMARY KEY (id));

ALTER TABLE public.flows ADD CONSTRAINT fk_flows_products FOREIGN KEY (product_id) REFERENCES public.products (id) ON DELETE CASCADE;

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-flows-table', 'jlpdeveloper', 'changelogs/initial_tables.yml', NOW(), 4, '9:ddd186b5d1cfd08188a1f69346fc3b3b', 'createTable tableName=flows; addForeignKeyConstraint baseTableName=flows, constraintName=fk_flows_products, referencedTableName=products', '', 'EXECUTED', NULL, 'v1.0.0', '5.0.2', '6565605040');

-- Changeset changelogs/initial_tables.yml::create-flow-steps-table::jlpdeveloper
CREATE TABLE public.flow_steps (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, flow_id INTEGER NOT NULL, current UUID NOT NULL, next UUID NOT NULL, CONSTRAINT flow_steps_pkey PRIMARY KEY (id));

ALTER TABLE public.flow_steps ADD CONSTRAINT fk_flow_steps_flows FOREIGN KEY (flow_id) REFERENCES public.flows (id) ON DELETE CASCADE;

ALTER TABLE public.flow_steps ADD CONSTRAINT uq_flow_steps_flow_current_next UNIQUE (flow_id, current, next);

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('create-flow-steps-table', 'jlpdeveloper', 'changelogs/initial_tables.yml', NOW(), 5, '9:5d57746fead4574a1fc879d9936a2751', 'createTable tableName=flow_steps; addForeignKeyConstraint baseTableName=flow_steps, constraintName=fk_flow_steps_flows, referencedTableName=flows; addUniqueConstraint constraintName=uq_flow_steps_flow_current_next, tableName=flow_steps', '', 'EXECUTED', NULL, 'v1.0.0', '5.0.2', '6565605040');

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

