// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platform

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Flow struct {
	ID          int32
	ProductID   int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type FlowStep struct {
	ID      int32
	FlowID  int32
	Current pgtype.UUID
	Next    pgtype.UUID
}

type Platform struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Product struct {
	ID          int32
	PlatformID  int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
