// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows(product_id, name, description, created_at, updated_at)
VALUES($1, $2, $3, $4, $4)
RETURNING id, product_id, name, description, created_at, updated_at
`

type CreateFlowParams struct {
	ProductID   int                `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.TimeStamp,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlowStep = `-- name: CreateFlowStep :execrows
INSERT INTO flow_steps(flow_id, current, next, target, protocol, created_at, updated_at) VALUES($1, $2, $3, $4, $5, $6, $6)
`

type CreateFlowStepParams struct {
	FlowID    int                `json:"flow_id"`
	Current   pgtype.UUID        `json:"current"`
	Next      pgtype.UUID        `json:"next"`
	Target    pgtype.Text        `json:"target"`
	Protocol  pgtype.Text        `json:"protocol"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateFlowStep(ctx context.Context, arg CreateFlowStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFlowStep,
		arg.FlowID,
		arg.Current,
		arg.Next,
		arg.Target,
		arg.Protocol,
		arg.Timestamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFlow = `-- name: DeleteFlow :execrows
DELETE FROM flows WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFlowStep = `-- name: DeleteFlowStep :execrows
DELETE FROM flow_steps WHERE id = $1
`

func (q *Queries) DeleteFlowStep(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlowStep, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlow = `-- name: GetFlow :one
SELECT id, product_id, name, description, created_at, updated_at FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id int) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowSteps = `-- name: GetFlowSteps :many
SELECT id, flow_id, target, protocol, current, next, created_at, updated_at FROM flow_steps WHERE flow_id = $1
`

func (q *Queries) GetFlowSteps(ctx context.Context, flowID int) ([]FlowStep, error) {
	rows, err := q.db.Query(ctx, getFlowSteps, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowStep
	for rows.Next() {
		var i FlowStep
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Target,
			&i.Protocol,
			&i.Current,
			&i.Next,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowsByProduct = `-- name: GetFlowsByProduct :many
SELECT id, product_id, name, description, created_at, updated_at FROM flows WHERE product_id = $1
`

func (q *Queries) GetFlowsByProduct(ctx context.Context, productID int) ([]Flow, error) {
	rows, err := q.db.Query(ctx, getFlowsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductById = `-- name: GetProductById :one
SELECT id FROM products WHERE id = $1
`

func (q *Queries) GetProductById(ctx context.Context, id int) (int, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	err := row.Scan(&id)
	return id, err
}

const updateFlow = `-- name: UpdateFlow :execrows
UPDATE flows SET name = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdateFlowParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int                `json:"id"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFlow,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFlowStep = `-- name: UpdateFlowStep :execrows
UPDATE flow_steps SET target = $1, protocol = $2, updated_at = $3 WHERE id = $4
`

type UpdateFlowStepParams struct {
	Target    pgtype.Text        `json:"target"`
	Protocol  pgtype.Text        `json:"protocol"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        int                `json:"id"`
}

func (q *Queries) UpdateFlowStep(ctx context.Context, arg UpdateFlowStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFlowStep,
		arg.Target,
		arg.Protocol,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
