// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error)
	CreateFlowStep(ctx context.Context, arg CreateFlowStepParams) (FlowStep, error)
	DeleteFlow(ctx context.Context, id int) (int64, error)
	DeleteFlowStep(ctx context.Context, id int) (int64, error)
	GetFlow(ctx context.Context, id int) (Flow, error)
	GetFlowStep(ctx context.Context, id int) (FlowStep, error)
	GetFlowSteps(ctx context.Context, flowID int) ([]FlowStep, error)
	GetFlowsByProduct(ctx context.Context, productID int) ([]Flow, error)
	GetProductById(ctx context.Context, id int) (int, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) (int64, error)
	UpdateFlowStep(ctx context.Context, arg UpdateFlowStepParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
