// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flows.sql

package flow

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlow = `-- name: CreateFlow :exec
INSERT INTO flows(product_id, name, description, created_at, updated_at)
VALUES($1, $2, $3, $4, $4)
`

type CreateFlowParams struct {
	ProductID   int                `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	TimeStamp   pgtype.Timestamptz `json:"time_stamp"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) error {
	_, err := q.db.Exec(ctx, createFlow,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.TimeStamp,
	)
	return err
}

const createFlowStep = `-- name: CreateFlowStep :exec
INSERT INTO flow_steps(flow_id, current, next) VALUES($1, $2, $3) RETURNING id
`

type CreateFlowStepParams struct {
	FlowID  int         `json:"flow_id"`
	Current pgtype.UUID `json:"current"`
	Next    pgtype.UUID `json:"next"`
}

func (q *Queries) CreateFlowStep(ctx context.Context, arg CreateFlowStepParams) error {
	_, err := q.db.Exec(ctx, createFlowStep, arg.FlowID, arg.Current, arg.Next)
	return err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteFlow(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteFlow, id)
	return err
}

const deleteFlowStep = `-- name: DeleteFlowStep :exec
DELETE FROM flow_steps WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteFlowStep(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteFlowStep, id)
	return err
}

const getFlow = `-- name: GetFlow :one
SELECT id, name, description, created_at, updated_at FROM flows WHERE id = $1
`

type GetFlowRow struct {
	ID          int                `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFlow(ctx context.Context, id int) (GetFlowRow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i GetFlowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowSteps = `-- name: GetFlowSteps :many
SELECT id, flow_id, current, next FROM flow_steps WHERE flow_id = $1
`

func (q *Queries) GetFlowSteps(ctx context.Context, flowID int) ([]FlowStep, error) {
	rows, err := q.db.Query(ctx, getFlowSteps, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowStep
	for rows.Next() {
		var i FlowStep
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Current,
			&i.Next,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowsByProduct = `-- name: GetFlowsByProduct :many
SELECT id, name, description, created_at, updated_at FROM flows WHERE product_id = $1
`

type GetFlowsByProductRow struct {
	ID          int                `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFlowsByProduct(ctx context.Context, productID int) ([]GetFlowsByProductRow, error) {
	rows, err := q.db.Query(ctx, getFlowsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowsByProductRow
	for rows.Next() {
		var i GetFlowsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :exec
UPDATE flows SET name = $1, description = $2, updated_at = $3 WHERE id = $4 RETURNING id
`

type UpdateFlowParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int                `json:"id"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) error {
	_, err := q.db.Exec(ctx, updateFlow,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
