// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package flow

import (
	"context"
)

type Querier interface {
	CreateFlow(ctx context.Context, arg CreateFlowParams) error
	CreateFlowStep(ctx context.Context, arg CreateFlowStepParams) error
	DeleteFlow(ctx context.Context, id int) error
	DeleteFlowStep(ctx context.Context, id int) error
	GetFlow(ctx context.Context, id int) (GetFlowRow, error)
	GetFlowSteps(ctx context.Context, flowID int) ([]FlowStep, error)
	GetFlowsByProduct(ctx context.Context, productID int) ([]GetFlowsByProductRow, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) error
}

var _ Querier = (*Queries)(nil)
