// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Flow struct {
	ID          int32              `json:"id"`
	ProductID   int32              `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FlowStep struct {
	ID      int32       `json:"id"`
	FlowID  int32       `json:"flow_id"`
	Current pgtype.UUID `json:"current"`
	Next    pgtype.UUID `json:"next"`
}

type Platform struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          int32              `json:"id"`
	PlatformID  int32              `json:"platform_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
