// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capabilities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCapability = `-- name: CreateCapability :one
INSERT INTO capabilities(product_id, name, description, created_at, updated_at)
VALUES($1, $2, $3, $4, $4)
RETURNING id, product_id, name, description, created_at, updated_at
`

type CreateCapabilityParams struct {
	ProductID   int                `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error) {
	row := q.db.QueryRow(ctx, createCapability,
		arg.ProductID,
		arg.Name,
		arg.Description,
		arg.Timestamp,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCapabilityStep = `-- name: CreateCapabilityStep :one
INSERT INTO capability_steps(capability_id, flow_step_id, protocol, target, created_at, updated_at)
VALUES($1, $2, $3, $4, $5, $5)
RETURNING id, capability_id, flow_step_id, protocol, target, created_at, updated_at
`

type CreateCapabilityStepParams struct {
	CapabilityID int                `json:"capability_id"`
	FlowStepID   int                `json:"flow_step_id"`
	Protocol     pgtype.Text        `json:"protocol"`
	Target       pgtype.Text        `json:"target"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateCapabilityStep(ctx context.Context, arg CreateCapabilityStepParams) (CapabilityStep, error) {
	row := q.db.QueryRow(ctx, createCapabilityStep,
		arg.CapabilityID,
		arg.FlowStepID,
		arg.Protocol,
		arg.Target,
		arg.Timestamp,
	)
	var i CapabilityStep
	err := row.Scan(
		&i.ID,
		&i.CapabilityID,
		&i.FlowStepID,
		&i.Protocol,
		&i.Target,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCapability = `-- name: DeleteCapability :execrows
DELETE FROM capabilities WHERE id = $1
`

func (q *Queries) DeleteCapability(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCapability, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCapabilityStep = `-- name: DeleteCapabilityStep :execrows
DELETE FROM capability_steps WHERE capability_id = $1
`

func (q *Queries) DeleteCapabilityStep(ctx context.Context, capabilityID int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCapabilityStep, capabilityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCapabilitiesByFlow = `-- name: GetCapabilitiesByFlow :many
SELECT DISTINCT
    c.id,
    c.product_id,
    c.name,
    c.description,
    c.created_at,
    c.updated_at,
    f.name AS flow_name
FROM capabilities c
join capability_steps cs on c.id = cs.capability_id
join flow_steps fs on cs.flow_step_id = fs.id
join flows f on fs.flow_id = f.id
where f.id = $1
`

type GetCapabilitiesByFlowRow struct {
	ID          int                `json:"id"`
	ProductID   int                `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	FlowName    string             `json:"flow_name"`
}

func (q *Queries) GetCapabilitiesByFlow(ctx context.Context, flowID int) ([]GetCapabilitiesByFlowRow, error) {
	rows, err := q.db.Query(ctx, getCapabilitiesByFlow, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCapabilitiesByFlowRow
	for rows.Next() {
		var i GetCapabilitiesByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlowName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapabilitiesByProduct = `-- name: GetCapabilitiesByProduct :many
SELECT id, product_id, name, description, created_at, updated_at
FROM capabilities c
WHERE product_id = $1
`

func (q *Queries) GetCapabilitiesByProduct(ctx context.Context, productID int) ([]Capability, error) {
	rows, err := q.db.Query(ctx, getCapabilitiesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Capability
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapability = `-- name: GetCapability :one
SELECT id, product_id, name, description, created_at, updated_at FROM capabilities WHERE id = $1
`

func (q *Queries) GetCapability(ctx context.Context, id int) (Capability, error) {
	row := q.db.QueryRow(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapabilitySteps = `-- name: GetCapabilitySteps :many
SELECT id, capability_id, flow_step_id, protocol, target, created_at, updated_at FROM capability_steps WHERE capability_id = $1
`

func (q *Queries) GetCapabilitySteps(ctx context.Context, capabilityID int) ([]CapabilityStep, error) {
	rows, err := q.db.Query(ctx, getCapabilitySteps, capabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CapabilityStep
	for rows.Next() {
		var i CapabilityStep
		if err := rows.Scan(
			&i.ID,
			&i.CapabilityID,
			&i.FlowStepID,
			&i.Protocol,
			&i.Target,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlow = `-- name: GetFlow :one
SELECT name FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id int) (string, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getFlowStep = `-- name: GetFlowStep :one
SELECT id, flow_id, current, next, created_at, updated_at FROM flow_steps WHERE id = $1
`

func (q *Queries) GetFlowStep(ctx context.Context, id int) (FlowStep, error) {
	row := q.db.QueryRow(ctx, getFlowStep, id)
	var i FlowStep
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Current,
		&i.Next,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowsFromSteps = `-- name: GetFlowsFromSteps :many
SELECT DISTINCT flow_id from flow_steps fs
JOIN capability_steps cs on fs.id = cs.flow_step_id
WHERE cs.capability_id = $1
`

func (q *Queries) GetFlowsFromSteps(ctx context.Context, capabilityID int) ([]int, error) {
	rows, err := q.db.Query(ctx, getFlowsFromSteps, capabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var flow_id int
		if err := rows.Scan(&flow_id); err != nil {
			return nil, err
		}
		items = append(items, flow_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT name FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int) (string, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateCapability = `-- name: UpdateCapability :execrows
UPDATE capabilities SET name = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdateCapabilityParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int                `json:"id"`
}

func (q *Queries) UpdateCapability(ctx context.Context, arg UpdateCapabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCapability,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
