// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capabilities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCapability = `-- name: CreateCapability :one
INSERT INTO capabilities(flow_id, name, description, created_at, updated_at)
VALUES($1, $2, $3, $4, $4)
RETURNING id, flow_id, name, description, created_at, updated_at
`

type CreateCapabilityParams struct {
	FlowID      int                `json:"flow_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error) {
	row := q.db.QueryRow(ctx, createCapability,
		arg.FlowID,
		arg.Name,
		arg.Description,
		arg.Timestamp,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCapability = `-- name: DeleteCapability :execrows
DELETE FROM capabilities WHERE id = $1
`

func (q *Queries) DeleteCapability(ctx context.Context, id int) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCapability, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCapabilitiesByProduct = `-- name: GetCapabilitiesByProduct :many
SELECT
    c.id,
    c.flow_id,
    c.name,
    f.name as flow_name,
    c.created_at,
    c.updated_at
FROM capabilities c
INNER JOIN flows f ON f.id = c.flow_id
WHERE f.product_id = $1
`

type GetCapabilitiesByProductRow struct {
	ID        int                `json:"id"`
	FlowID    int                `json:"flow_id"`
	Name      string             `json:"name"`
	FlowName  string             `json:"flow_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCapabilitiesByProduct(ctx context.Context, productID int) ([]GetCapabilitiesByProductRow, error) {
	rows, err := q.db.Query(ctx, getCapabilitiesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCapabilitiesByProductRow
	for rows.Next() {
		var i GetCapabilitiesByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Name,
			&i.FlowName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapability = `-- name: GetCapability :one
SELECT id, flow_id, name, description, created_at, updated_at FROM capabilities WHERE id = $1
`

func (q *Queries) GetCapability(ctx context.Context, id int) (Capability, error) {
	row := q.db.QueryRow(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlow = `-- name: GetFlow :one
SELECT name FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id int) (string, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateCapability = `-- name: UpdateCapability :execrows
UPDATE capabilities SET name = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdateCapabilityParams struct {
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          int                `json:"id"`
}

func (q *Queries) UpdateCapability(ctx context.Context, arg UpdateCapabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCapability,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
