// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Capability struct {
	ID          int                `json:"id"`
	ProductID   int                `json:"product_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CapabilityStep struct {
	ID           int                `json:"id"`
	CapabilityID int                `json:"capability_id"`
	FlowStepID   int                `json:"flow_step_id"`
	Protocol     pgtype.Text        `json:"protocol"`
	Target       pgtype.Text        `json:"target"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
