// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error)
	DeleteCapability(ctx context.Context, id int) (int64, error)
	GetCapabilitiesByProduct(ctx context.Context, productID int) ([]GetCapabilitiesByProductRow, error)
	GetCapability(ctx context.Context, id int) (Capability, error)
	GetFlow(ctx context.Context, id int) (string, error)
	UpdateCapability(ctx context.Context, arg UpdateCapabilityParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
