// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	DeleteProduct(ctx context.Context, id int32) (int32, error)
	GetProductById(ctx context.Context, id int32) (Product, error)
	GetProductsByPlatform(ctx context.Context, platformID int32) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
