// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platforms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatform = `-- name: CreatePlatform :exec
INSERT INTO platforms (name, description, created_at, updated_at) VALUES ($1, $2, $3, $3)
`

type CreatePlatformParams struct {
	Name        string
	Description pgtype.Text
	Timestamp   pgtype.Timestamptz
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) error {
	_, err := q.db.Exec(ctx, createPlatform, arg.Name, arg.Description, arg.Timestamp)
	return err
}

const deletePlatform = `-- name: DeletePlatform :one
DELETE FROM platforms WHERE id = $1 RETURNING id
`

func (q *Queries) DeletePlatform(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deletePlatform, id)
	err := row.Scan(&id)
	return id, err
}

const getPlatform = `-- name: GetPlatform :one
SELECT id, name, description, created_at, updated_at FROM platforms WHERE id = $1
`

func (q *Queries) GetPlatform(ctx context.Context, id int32) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatform, id)
	var i Platform
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatforms = `-- name: GetPlatforms :many
SELECT id, name, description, created_at, updated_at FROM platforms order by id
`

func (q *Queries) GetPlatforms(ctx context.Context) ([]Platform, error) {
	rows, err := q.db.Query(ctx, getPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Platform
	for rows.Next() {
		var i Platform
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlatform = `-- name: UpdatePlatform :exec
UPDATE platforms SET name = $1, description = $2, updated_at = $3 WHERE id = $4
`

type UpdatePlatformParams struct {
	Name        string
	Description pgtype.Text
	Updatedat   pgtype.Timestamptz
	ID          int32
}

func (q *Queries) UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) error {
	_, err := q.db.Exec(ctx, updatePlatform,
		arg.Name,
		arg.Description,
		arg.Updatedat,
		arg.ID,
	)
	return err
}
