package db

import (
	"context"
	"products/internal/db/platform"
	"products/internal/db/product"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type Store struct {
	Platform *platform.Queries
	Product  *product.Queries
}

func New(db DBTX) *Store {
	return &Store{
		Platform: platform.New(db),
		Product:  product.New(db),
	}
}

// This interface is repeated in every db package, it is auto-generated by sqlc
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}
