// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package platform

import (
	"context"
)

type Querier interface {
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) error
	DeletePlatform(ctx context.Context, id int32) (int32, error)
	GetPlatform(ctx context.Context, id int32) (Platform, error)
	GetPlatforms(ctx context.Context) ([]Platform, error)
	UpdatePlatform(ctx context.Context, arg UpdatePlatformParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
